import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Checkout - Top One Futures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-dark relative min-h-screen`}>
        <div className="absolute top-0 left-1/2 transform -translate-1/2 w-full">
          <Image src="/images/tof-dots.png" alt="Logo" width={1300} height={1300} className="bg-transparent w-full" />
        </div>
        <div className="absolute w-1/2 aspect-square top-0 left-1/2 transform -translate-x-1/3 -translate-y-1/2 bg-neon-green/5 rounded-full blur-3xl"></div>
        <main className="relative">
          <Header />
          <main className="p-6">
            <div className="w-full max-w-6xl mx-auto">
              {children}
            </div>
          </main>
          <Footer />
        </main>
      </body>
    </html>
  );
}
