export const countries = [
  { code: "af", value: "Afghanistan", label: "Afghanistan" },
  { code: "al", value: "Albania", label: "Albania" },
  { code: "dz", value: "Algeria", label: "Algeria" },
  { code: "as", value: "American Samoa", label: "American Samoa" },
  { code: "ad", value: "Andorra", label: "Andorra" },
  { code: "ao", value: "Angola", label: "Angola" },
  { code: "ai", value: "Anguilla", label: "Anguilla" },
  { code: "aq", value: "Antarctica", label: "Antarctica" },
  { code: "ag", value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { code: "ar", value: "Argentina", label: "Argentina" },
  { code: "am", value: "Armenia", label: "Armenia" },
  { code: "aw", value: "Aruba", label: "Aruba" },
  { code: "au", value: "Australia", label: "Australia" },
  { code: "at", value: "Austria", label: "Austria" },
  { code: "az", value: "Azerbaijan", label: "Azerbaijan" },
  { code: "bs", value: "Bahamas", label: "Bahamas" },
  { code: "bh", value: "Bahrain", label: "Bahrain" },
  { code: "bd", value: "Bangladesh", label: "Bangladesh" },
  { code: "bb", value: "Barbados", label: "Barbados" },
  { code: "by", value: "Belarus", label: "Belarus" },
  { code: "be", value: "Belgium", label: "Belgium" },
  { code: "bz", value: "Belize", label: "Belize" },
  { code: "bj", value: "Benin", label: "Benin" },
  { code: "bm", value: "Bermuda", label: "Bermuda" },
  { code: "bt", value: "Bhutan", label: "Bhutan" },
  { code: "bo", value: "Bolivia", label: "Bolivia" },
  { code: "ba", value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { code: "bw", value: "Botswana", label: "Botswana" },
  { code: "bv", value: "Bouvet Island", label: "Bouvet Island" },
  { code: "br", value: "Brazil", label: "Brazil" },
  // { code: "io", value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
  { code: "bn", value: "Brunei Darussalam", label: "Brunei Darussalam" },
  { code: "bg", value: "Bulgaria", label: "Bulgaria" },
  { code: "bf", value: "Burkina Faso", label: "Burkina Faso" },
  { code: "bi", value: "Burundi", label: "Burundi" },
  { code: "kh", value: "Cambodia", label: "Cambodia" },
  { code: "cm", value: "Cameroon", label: "Cameroon" },
  { code: "ca", value: "Canada", label: "Canada" },
  { code: "cv", value: "Cape Verde", label: "Cape Verde" },
  { code: "ky", value: "Cayman Islands", label: "Cayman Islands" },
  { code: "cf", value: "Central African Republic", label: "Central African Republic" },
  { code: "td", value: "Chad", label: "Chad" },
  { code: "cl", value: "Chile", label: "Chile" },
  { code: "cn", value: "China", label: "China" },
  { code: "cx", value: "Christmas Island", label: "Christmas Island" },
  { code: "cc", value: "Cocos Islands", label: "Cocos Islands" },
  { code: "co", value: "Colombia", label: "Colombia" },
  { code: "km", value: "Comoros", label: "Comoros" },
  { code: "cg", value: "Congo", label: "Congo" },
  { code: "cd", value: "Congo", label: "Congo" },
  { code: "ck", value: "Cook Islands", label: "Cook Islands" },
  { code: "cr", value: "Costa Rica", label: "Costa Rica" },
  { code: "ci", value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { code: "hr", value: "Croatia", label: "Croatia" },
  { code: "cu", value: "Cuba", label: "Cuba" },
  { code: "cw", value: "Curaçao", label: "Curaçao" },
  { code: "cy", value: "Cyprus", label: "Cyprus" },
  { code: "cz", value: "Czechia", label: "Czechia" },
  { code: "dk", value: "Denmark", label: "Denmark" },
  { code: "dj", value: "Djibouti", label: "Djibouti" },
  { code: "dm", value: "Dominica", label: "Dominica" },
  { code: "do", value: "Dominican Republic", label: "Dominican Republic" },
  { code: "ec", value: "Ecuador", label: "Ecuador" },
  { code: "eg", value: "Egypt", label: "Egypt" },
  { code: "sv", value: "El Salvador", label: "El Salvador" },
  { code: "gq", value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { code: "er", value: "Eritrea", label: "Eritrea" },
  { code: "ee", value: "Estonia", label: "Estonia" },
  { code: "sz", value: "Eswatini", label: "Eswatini" },
  { code: "et", value: "Ethiopia", label: "Ethiopia" },
  { code: "fk", value: "Malvinas", label: "Malvinas" },
  { code: "fo", value: "Faroe Islands", label: "Faroe Islands" },
  { code: "fj", value: "Fiji", label: "Fiji" },
  { code: "fi", value: "Finland", label: "Finland" },
  { code: "fr", value: "France", label: "France" },
  { code: "gf", value: "French Guiana", label: "French Guiana" },
  { code: "pf", value: "French Polynesia", label: "French Polynesia" },
  { code: "tf", value: "French Southern Territories", label: "French Southern Territories" },
  { code: "ga", value: "Gabon", label: "Gabon" },
  { code: "gm", value: "Gambia", label: "Gambia" },
  { code: "ge", value: "Georgia", label: "Georgia" },
  { code: "de", value: "Germany", label: "Germany" },
  { code: "gh", value: "Ghana", label: "Ghana" },
  { code: "gi", value: "Gibraltar", label: "Gibraltar" },
  { code: "gr", value: "Greece", label: "Greece" },
  { code: "gl", value: "Greenland", label: "Greenland" },
  { code: "gd", value: "Grenada", label: "Grenada" },
  { code: "gp", value: "Guadeloupe", label: "Guadeloupe" },
  { code: "gu", value: "Guam", label: "Guam" },
  { code: "gt", value: "Guatemala", label: "Guatemala" },
  { code: "gg", value: "Guernsey", label: "Guernsey" },
  { code: "gn", value: "Guinea", label: "Guinea" },
  { code: "gw", value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { code: "gy", value: "Guyana", label: "Guyana" },
  { code: "ht", value: "Haiti", label: "Haiti" },
  // { code: "hm", value: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands" },
  { code: "va", value: "Holy See", label: "Holy See" },
  { code: "hn", value: "Honduras", label: "Honduras" },
  { code: "hk", value: "Hong Kong", label: "Hong Kong" },
  { code: "hu", value: "Hungary", label: "Hungary" },
  { code: "is", value: "Iceland", label: "Iceland" },
  { code: "in", value: "India", label: "India" },
  { code: "id", value: "Indonesia", label: "Indonesia" },
  { code: "ir", value: "Iran", label: "Iran" },
  { code: "iq", value: "Iraq", label: "Iraq" },
  { code: "ie", value: "Ireland", label: "Ireland" },
  { code: "im", value: "Isle of Man", label: "Isle of Man" },
  { code: "il", value: "Israel", label: "Israel" },
  { code: "it", value: "Italy", label: "Italy" },
  { code: "jm", value: "Jamaica", label: "Jamaica" },
  { code: "jp", value: "Japan", label: "Japan" },
  { code: "je", value: "Jersey", label: "Jersey" },
  { code: "jo", value: "Jordan", label: "Jordan" },
  { code: "kz", value: "Kazakhstan", label: "Kazakhstan" },
  { code: "ke", value: "Kenya", label: "Kenya" },
  { code: "ki", value: "Kiribati", label: "Kiribati" },
  { code: "kp", value: "North Korea", label: "North Korea" },
  { code: "kr", value: "South Korea", label: "South Korea" },
  { code: "kw", value: "Kuwait", label: "Kuwait" },
  { code: "kg", value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { code: "la", value: "Laos", label: "Laos" },
  { code: "lv", value: "Latvia", label: "Latvia" },
  { code: "lb", value: "Lebanon", label: "Lebanon" },
  { code: "ls", value: "Lesotho", label: "Lesotho" },
  { code: "lr", value: "Liberia", label: "Liberia" },
  { code: "ly", value: "Libya", label: "Libya" },
  { code: "li", value: "Liechtenstein", label: "Liechtenstein" },
  { code: "lt", value: "Lithuania", label: "Lithuania" },
  { code: "lu", value: "Luxembourg", label: "Luxembourg" },
  { code: "mo", value: "Macao", label: "Macao" },
  { code: "mg", value: "Madagascar", label: "Madagascar" },
  { code: "mw", value: "Malawi", label: "Malawi" },
  { code: "my", value: "Malaysia", label: "Malaysia" },
  { code: "mv", value: "Maldives", label: "Maldives" },
  { code: "ml", value: "Mali", label: "Mali" },
  { code: "mt", value: "Malta", label: "Malta" },
  { code: "mh", value: "Marshall Islands", label: "Marshall Islands" },
  { code: "mq", value: "Martinique", label: "Martinique" },
  { code: "mr", value: "Mauritania", label: "Mauritania" },
  { code: "mu", value: "Mauritius", label: "Mauritius" },
  { code: "yt", value: "Mayotte", label: "Mayotte" },
  { code: "mx", value: "Mexico", label: "Mexico" },
  { code: "fm", value: "Micronesia", label: "Micronesia" },
  { code: "md", value: "Moldova", label: "Moldova" },
  { code: "mc", value: "Monaco", label: "Monaco" },
  { code: "mn", value: "Mongolia", label: "Mongolia" },
  { code: "me", value: "Montenegro", label: "Montenegro" },
  { code: "ms", value: "Montserrat", label: "Montserrat" },
  { code: "ma", value: "Morocco", label: "Morocco" },
  { code: "mz", value: "Mozambique", label: "Mozambique" },
  { code: "mm", value: "Myanmar", label: "Myanmar" },
  { code: "na", value: "Namibia", label: "Namibia" },
  { code: "nr", value: "Nauru", label: "Nauru" },
  { code: "np", value: "Nepal", label: "Nepal" },
  { code: "nl", value: "Netherlands", label: "Netherlands" },
  { code: "nc", value: "New Caledonia", label: "New Caledonia" },
  { code: "nz", value: "New Zealand", label: "New Zealand" },
  { code: "ni", value: "Nicaragua", label: "Nicaragua" },
  { code: "ne", value: "Niger", label: "Niger" },
  { code: "ng", value: "Nigeria", label: "Nigeria" },
  { code: "nu", value: "Niue", label: "Niue" },
  { code: "nf", value: "Norfolk Island", label: "Norfolk Island" },
  { code: "mp", value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
  { code: "no", value: "Norway", label: "Norway" },
  { code: "om", value: "Oman", label: "Oman" },
  { code: "pk", value: "Pakistan", label: "Pakistan" },
  { code: "pw", value: "Palau", label: "Palau" },
  { code: "ps", value: "Palestine", label: "Palestine" },
  { code: "pa", value: "Panama", label: "Panama" },
  { code: "pg", value: "Papua New Guinea", label: "Papua New Guinea" },
  { code: "py", value: "Paraguay", label: "Paraguay" },
  { code: "pe", value: "Peru", label: "Peru" },
  { code: "ph", value: "Philippines", label: "Philippines" },
  { code: "pn", value: "Pitcairn", label: "Pitcairn" },
  { code: "pl", value: "Poland", label: "Poland" },
  { code: "pt", value: "Portugal", label: "Portugal" },
  { code: "pr", value: "Puerto Rico", label: "Puerto Rico" },
  { code: "qa", value: "Qatar", label: "Qatar" },
  { code: "re", value: "Réunion", label: "Réunion" },
  { code: "ro", value: "Romania", label: "Romania" },
  { code: "ru", value: "Russian Federation", label: "Russian Federation" },
  { code: "rw", value: "Rwanda", label: "Rwanda" },
  { code: "bl", value: "St Barthélemy", label: "St Barthélemy" },
  { code: "sh", value: "St Helena", label: "St Helena" },
  { code: "kn", value: "St Kitts and Nevis", label: "St Kitts and Nevis" },
  { code: "lc", value: "St Lucia", label: "St Lucia" },
  { code: "mf", value: "St Martin", label: "St Martin" },
  { code: "pm", value: "St Pierre and Miquelon", label: "St Pierre and Miquelon" },
  { code: "vc", value: "St Vincent and the Grenadines", label: "St Vincent and the Grenadines" },
  { code: "ws", value: "Samoa", label: "Samoa" },
  { code: "sm", value: "San Marino", label: "San Marino" },
  { code: "st", value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { code: "sa", value: "Saudi Arabia", label: "Saudi Arabia" },
  { code: "sn", value: "Senegal", label: "Senegal" },
  { code: "rs", value: "Serbia", label: "Serbia" },
  { code: "sc", value: "Seychelles", label: "Seychelles" },
  { code: "sl", value: "Sierra Leone", label: "Sierra Leone" },
  { code: "sg", value: "Singapore", label: "Singapore" },
  { code: "sx", value: "Sint Maarten", label: "Sint Maarten" },
  { code: "sk", value: "Slovakia", label: "Slovakia" },
  { code: "si", value: "Slovenia", label: "Slovenia" },
  { code: "sb", value: "Solomon Islands", label: "Solomon Islands" },
  { code: "so", value: "Somalia", label: "Somalia" },
  { code: "za", value: "South Africa", label: "South Africa" },
  // { code: "gs", value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands" },
  { code: "ss", value: "South Sudan", label: "South Sudan" },
  { code: "es", value: "Spain", label: "Spain" },
  { code: "lk", value: "Sri Lanka", label: "Sri Lanka" },
  { code: "sd", value: "Sudan", label: "Sudan" },
  { code: "sr", value: "Suriname", label: "Suriname" },
  { code: "sj", value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen" },
  { code: "se", value: "Sweden", label: "Sweden" },
  { code: "ch", value: "Switzerland", label: "Switzerland" },
  { code: "sy", value: "Syrian Arab Republic", label: "Syrian Arab Republic" },
  { code: "tw", value: "Taiwan", label: "Taiwan" },
  { code: "tj", value: "Tajikistan", label: "Tajikistan" },
  { code: "tz", value: "Tanzania", label: "Tanzania" },
  { code: "th", value: "Thailand", label: "Thailand" },
  { code: "tl", value: "Timor-Leste", label: "Timor-Leste" },
  { code: "tg", value: "Togo", label: "Togo" },
  { code: "tk", value: "Tokelau", label: "Tokelau" },
  { code: "to", value: "Tonga", label: "Tonga" },
  { code: "tt", value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { code: "tn", value: "Tunisia", label: "Tunisia" },
  { code: "tr", value: "Turkey", label: "Turkey" },
  { code: "tm", value: "Turkmenistan", label: "Turkmenistan" },
  { code: "tv", value: "Tuvalu", label: "Tuvalu" },
  { code: "ug", value: "Uganda", label: "Uganda" },
  { code: "ua", value: "Ukraine", label: "Ukraine" },
  { code: "ae", value: "United Arab Emirates", label: "United Arab Emirates" },
  { code: "gb-ukm", value: "United Kingdom", label: "United Kingdom" },
  { code: "us", value: "United States", label: "United States" },
  { code: "uy", value: "Uruguay", label: "Uruguay" },
  { code: "uz", value: "Uzbekistan", label: "Uzbekistan" },
  { code: "vu", value: "Vanuatu", label: "Vanuatu" },
  { code: "ve", value: "Venezuela", label: "Venezuela" },
  { code: "vn", value: "Viet Nam", label: "Viet Nam" },
  { code: "vg", value: "Virgin Islands", label: "Virgin Islands" },
  { code: "wf", value: "Wallis and Futuna", label: "Wallis and Futuna" },
  { code: "eh", value: "Western Sahara", label: "Western Sahara" },
  { code: "ye", value: "Yemen", label: "Yemen" },
  { code: "zm", value: "Zambia", label: "Zambia" },
  { code: "zw", value: "Zimbabwe", label: "Zimbabwe" },
]

export const getCountryByCode = (code: string) => {
  return countries.find((country) => country.code === code)
}