export const countries = [
  { code: "af", value: "Afghanistan", label: "Afghanistan", phoneCode: "+93" },
  { code: "al", value: "Albania", label: "Albania", phoneCode: "+355" },
  { code: "dz", value: "Algeria", label: "Algeria", phoneCode: "+213" },
  { code: "as", value: "American Samoa", label: "American Samoa", phoneCode: "+1684" },
  { code: "ad", value: "Andorra", label: "Andorra", phoneCode: "+376" },
  { code: "ao", value: "Angola", label: "Angola", phoneCode: "+244" },
  { code: "ai", value: "Anguilla", label: "Anguilla", phoneCode: "+1264" },
  { code: "aq", value: "Antarctica", label: "Antarctica", phoneCode: "+672" },
  { code: "ag", value: "Antigua and Barbuda", label: "Antigua and Barbuda", phoneCode: "+1268" },
  { code: "ar", value: "Argentina", label: "Argentina", phoneCode: "+54" },
  { code: "am", value: "Armenia", label: "Armenia", phoneCode: "+374" },
  { code: "aw", value: "Aruba", label: "Aruba", phoneCode: "+297" },
  { code: "au", value: "Australia", label: "Australia", phoneCode: "+61" },
  { code: "at", value: "Austria", label: "Austria", phoneCode: "+43" },
  { code: "az", value: "Azerbaijan", label: "Azerbaijan", phoneCode: "+994" },
  { code: "bs", value: "Bahamas", label: "Bahamas", phoneCode: "+1242" },
  { code: "bh", value: "Bahrain", label: "Bahrain", phoneCode: "+973" },
  { code: "bd", value: "Bangladesh", label: "Bangladesh", phoneCode: "+880" },
  { code: "bb", value: "Barbados", label: "Barbados", phoneCode: "+1246" },
  { code: "by", value: "Belarus", label: "Belarus", phoneCode: "+375" },
  { code: "be", value: "Belgium", label: "Belgium", phoneCode: "+32" },
  { code: "bz", value: "Belize", label: "Belize", phoneCode: "+501" },
  { code: "bj", value: "Benin", label: "Benin", phoneCode: "+229" },
  { code: "bm", value: "Bermuda", label: "Bermuda", phoneCode: "+1441" },
  { code: "bt", value: "Bhutan", label: "Bhutan", phoneCode: "+975" },
  { code: "bo", value: "Bolivia", label: "Bolivia", phoneCode: "+591" },
  { code: "ba", value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", phoneCode: "+387" },
  { code: "bw", value: "Botswana", label: "Botswana", phoneCode: "+267" },
  { code: "bv", value: "Bouvet Island", label: "Bouvet Island", phoneCode: "+47" },
  { code: "br", value: "Brazil", label: "Brazil", phoneCode: "+55" },
  // { code: "io", value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
  { code: "bn", value: "Brunei Darussalam", label: "Brunei Darussalam", phoneCode: "+673" },
  { code: "bg", value: "Bulgaria", label: "Bulgaria", phoneCode: "+359" },
  { code: "bf", value: "Burkina Faso", label: "Burkina Faso", phoneCode: "+226" },
  { code: "bi", value: "Burundi", label: "Burundi", phoneCode: "+257" },
  { code: "kh", value: "Cambodia", label: "Cambodia", phoneCode: "+855" },
  { code: "cm", value: "Cameroon", label: "Cameroon", phoneCode: "+237" },
  { code: "ca", value: "Canada", label: "Canada", phoneCode: "+1" },
  { code: "cv", value: "Cape Verde", label: "Cape Verde", phoneCode: "+238" },
  { code: "ky", value: "Cayman Islands", label: "Cayman Islands", phoneCode: "+1345" },
  { code: "cf", value: "Central African Republic", label: "Central African Republic", phoneCode: "+236" },
  { code: "td", value: "Chad", label: "Chad", phoneCode: "+235" },
  { code: "cl", value: "Chile", label: "Chile", phoneCode: "+56" },
  { code: "cn", value: "China", label: "China", phoneCode: "+86" },
  { code: "cx", value: "Christmas Island", label: "Christmas Island", phoneCode: "+61" },
  { code: "cc", value: "Cocos Islands", label: "Cocos Islands", phoneCode: "+61" },
  { code: "co", value: "Colombia", label: "Colombia", phoneCode: "+57" },
  { code: "km", value: "Comoros", label: "Comoros", phoneCode: "+269" },
  { code: "cg", value: "Congo", label: "Congo", phoneCode: "+242" },
  { code: "cd", value: "Congo", label: "Congo", phoneCode: "+243" },
  { code: "ck", value: "Cook Islands", label: "Cook Islands", phoneCode: "+682" },
  { code: "cr", value: "Costa Rica", label: "Costa Rica", phoneCode: "+506" },
  { code: "ci", value: "Côte d'Ivoire", label: "Côte d'Ivoire", phoneCode: "+225" },
  { code: "hr", value: "Croatia", label: "Croatia", phoneCode: "+385" },
  { code: "cu", value: "Cuba", label: "Cuba", phoneCode: "+53" },
  { code: "cw", value: "Curaçao", label: "Curaçao", phoneCode: "+599" },
  { code: "cy", value: "Cyprus", label: "Cyprus", phoneCode: "+357" },
  { code: "cz", value: "Czechia", label: "Czechia", phoneCode: "+420" },
  { code: "dk", value: "Denmark", label: "Denmark", phoneCode: "+45" },
  { code: "dj", value: "Djibouti", label: "Djibouti", phoneCode: "+253" },
  { code: "dm", value: "Dominica", label: "Dominica", phoneCode: "+1767" },
  { code: "do", value: "Dominican Republic", label: "Dominican Republic", phoneCode: "+1809" },
  { code: "ec", value: "Ecuador", label: "Ecuador", phoneCode: "+593" },
  { code: "eg", value: "Egypt", label: "Egypt", phoneCode: "+20" },
  { code: "sv", value: "El Salvador", label: "El Salvador", phoneCode: "+503" },
  { code: "gq", value: "Equatorial Guinea", label: "Equatorial Guinea", phoneCode: "+240" },
  { code: "er", value: "Eritrea", label: "Eritrea", phoneCode: "+291" },
  { code: "ee", value: "Estonia", label: "Estonia", phoneCode: "+372" },
  { code: "sz", value: "Eswatini", label: "Eswatini", phoneCode: "+268" },
  { code: "et", value: "Ethiopia", label: "Ethiopia", phoneCode: "+251" },
  { code: "fk", value: "Malvinas", label: "Malvinas", phoneCode: "+500" },
  { code: "fo", value: "Faroe Islands", label: "Faroe Islands", phoneCode: "+298" },
  { code: "fj", value: "Fiji", label: "Fiji", phoneCode: "+679" },
  { code: "fi", value: "Finland", label: "Finland", phoneCode: "+358" },
  { code: "fr", value: "France", label: "France", phoneCode: "+33" },
  { code: "gf", value: "French Guiana", label: "French Guiana", phoneCode: "+594" },
  { code: "pf", value: "French Polynesia", label: "French Polynesia", phoneCode: "+689" },
  { code: "tf", value: "French Southern Territories", label: "French Southern Territories", phoneCode: "+262" },
  { code: "ga", value: "Gabon", label: "Gabon", phoneCode: "+241" },
  { code: "gm", value: "Gambia", label: "Gambia", phoneCode: "+220" },
  { code: "ge", value: "Georgia", label: "Georgia", phoneCode: "+995" },
  { code: "de", value: "Germany", label: "Germany", phoneCode: "+49" },
  { code: "gh", value: "Ghana", label: "Ghana", phoneCode: "+233" },
  { code: "gi", value: "Gibraltar", label: "Gibraltar", phoneCode: "+350" },
  { code: "gr", value: "Greece", label: "Greece", phoneCode: "+30" },
  { code: "gl", value: "Greenland", label: "Greenland", phoneCode: "+299" },
  { code: "gd", value: "Grenada", label: "Grenada", phoneCode: "+1473" },
  { code: "gp", value: "Guadeloupe", label: "Guadeloupe", phoneCode: "+590" },
  { code: "gu", value: "Guam", label: "Guam", phoneCode: "+1671" },
  { code: "gt", value: "Guatemala", label: "Guatemala", phoneCode: "+502" },
  { code: "gg", value: "Guernsey", label: "Guernsey", phoneCode: "+44" },
  { code: "gn", value: "Guinea", label: "Guinea", phoneCode: "+224" },
  { code: "gw", value: "Guinea-Bissau", label: "Guinea-Bissau", phoneCode: "+245" },
  { code: "gy", value: "Guyana", label: "Guyana", phoneCode: "+592" },
  { code: "ht", value: "Haiti", label: "Haiti", phoneCode: "+509" },
  // { code: "hm", value: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands" },
  { code: "va", value: "Holy See", label: "Holy See", phoneCode: "+379" },
  { code: "hn", value: "Honduras", label: "Honduras", phoneCode: "+504" },
  { code: "hk", value: "Hong Kong", label: "Hong Kong", phoneCode: "+852" },
  { code: "hu", value: "Hungary", label: "Hungary", phoneCode: "+36" },
  { code: "is", value: "Iceland", label: "Iceland", phoneCode: "+354" },
  { code: "in", value: "India", label: "India", phoneCode: "+91" },
  { code: "id", value: "Indonesia", label: "Indonesia", phoneCode: "+62" },
  { code: "ir", value: "Iran", label: "Iran", phoneCode: "+98" },
  { code: "iq", value: "Iraq", label: "Iraq", phoneCode: "+964" },
  { code: "ie", value: "Ireland", label: "Ireland", phoneCode: "+353" },
  { code: "im", value: "Isle of Man", label: "Isle of Man", phoneCode: "+44" },
  { code: "il", value: "Israel", label: "Israel", phoneCode: "+972" },
  { code: "it", value: "Italy", label: "Italy", phoneCode: "+39" },
  { code: "jm", value: "Jamaica", label: "Jamaica", phoneCode: "+1876" },
  { code: "jp", value: "Japan", label: "Japan", phoneCode: "+81" },
  { code: "je", value: "Jersey", label: "Jersey", phoneCode: "+44" },
  { code: "jo", value: "Jordan", label: "Jordan", phoneCode: "+962" },
  { code: "kz", value: "Kazakhstan", label: "Kazakhstan", phoneCode: "+7" },
  { code: "ke", value: "Kenya", label: "Kenya", phoneCode: "+254" },
  { code: "ki", value: "Kiribati", label: "Kiribati", phoneCode: "+686" },
  { code: "kp", value: "North Korea", label: "North Korea", phoneCode: "+850" },
  { code: "kr", value: "South Korea", label: "South Korea", phoneCode: "+82" },
  { code: "kw", value: "Kuwait", label: "Kuwait", phoneCode: "+965" },
  { code: "kg", value: "Kyrgyzstan", label: "Kyrgyzstan", phoneCode: "+996" },
  { code: "la", value: "Laos", label: "Laos", phoneCode: "+856" },
  { code: "lv", value: "Latvia", label: "Latvia", phoneCode: "+371" },
  { code: "lb", value: "Lebanon", label: "Lebanon", phoneCode: "+961" },
  { code: "ls", value: "Lesotho", label: "Lesotho", phoneCode: "+266" },
  { code: "lr", value: "Liberia", label: "Liberia", phoneCode: "+231" },
  { code: "ly", value: "Libya", label: "Libya", phoneCode: "+218" },
  { code: "li", value: "Liechtenstein", label: "Liechtenstein", phoneCode: "+423" },
  { code: "lt", value: "Lithuania", label: "Lithuania", phoneCode: "+370" },
  { code: "lu", value: "Luxembourg", label: "Luxembourg", phoneCode: "+352" },
  { code: "mo", value: "Macao", label: "Macao", phoneCode: "+853" },
  { code: "mg", value: "Madagascar", label: "Madagascar", phoneCode: "+261" },
  { code: "mw", value: "Malawi", label: "Malawi", phoneCode: "+265" },
  { code: "my", value: "Malaysia", label: "Malaysia", phoneCode: "+60" },
  { code: "mv", value: "Maldives", label: "Maldives", phoneCode: "+960" },
  { code: "ml", value: "Mali", label: "Mali", phoneCode: "+223" },
  { code: "mt", value: "Malta", label: "Malta", phoneCode: "+356" },
  { code: "mh", value: "Marshall Islands", label: "Marshall Islands", phoneCode: "+692" },
  { code: "mq", value: "Martinique", label: "Martinique", phoneCode: "+596" },
  { code: "mr", value: "Mauritania", label: "Mauritania", phoneCode: "+222" },
  { code: "mu", value: "Mauritius", label: "Mauritius", phoneCode: "+230" },
  { code: "yt", value: "Mayotte", label: "Mayotte", phoneCode: "+262" },
  { code: "mx", value: "Mexico", label: "Mexico", phoneCode: "+52" },
  { code: "fm", value: "Micronesia", label: "Micronesia", phoneCode: "+691" },
  { code: "md", value: "Moldova", label: "Moldova", phoneCode: "+373" },
  { code: "mc", value: "Monaco", label: "Monaco", phoneCode: "+377" },
  { code: "mn", value: "Mongolia", label: "Mongolia", phoneCode: "+976" },
  { code: "me", value: "Montenegro", label: "Montenegro", phoneCode: "+382" },
  { code: "ms", value: "Montserrat", label: "Montserrat", phoneCode: "+1664" },
  { code: "ma", value: "Morocco", label: "Morocco", phoneCode: "+212" },
  { code: "mz", value: "Mozambique", label: "Mozambique", phoneCode: "+258" },
  { code: "mm", value: "Myanmar", label: "Myanmar", phoneCode: "+95" },
  { code: "na", value: "Namibia", label: "Namibia", phoneCode: "+264" },
  { code: "nr", value: "Nauru", label: "Nauru", phoneCode: "+674" },
  { code: "np", value: "Nepal", label: "Nepal", phoneCode: "+977" },
  { code: "nl", value: "Netherlands", label: "Netherlands", phoneCode: "+31" },
  { code: "nc", value: "New Caledonia", label: "New Caledonia", phoneCode: "+687" },
  { code: "nz", value: "New Zealand", label: "New Zealand", phoneCode: "+64" },
  { code: "ni", value: "Nicaragua", label: "Nicaragua", phoneCode: "+505" },
  { code: "ne", value: "Niger", label: "Niger", phoneCode: "+227" },
  { code: "ng", value: "Nigeria", label: "Nigeria", phoneCode: "+234" },
  { code: "nu", value: "Niue", label: "Niue", phoneCode: "+683" },
  { code: "nf", value: "Norfolk Island", label: "Norfolk Island", phoneCode: "+672" },
  { code: "mp", value: "Northern Mariana Islands", label: "Northern Mariana Islands", phoneCode: "+1670" },
  { code: "no", value: "Norway", label: "Norway", phoneCode: "+47" },
  { code: "om", value: "Oman", label: "Oman", phoneCode: "+968" },
  { code: "pk", value: "Pakistan", label: "Pakistan", phoneCode: "+92" },
  { code: "pw", value: "Palau", label: "Palau", phoneCode: "+680" },
  { code: "ps", value: "Palestine", label: "Palestine", phoneCode: "+970" },
  { code: "pa", value: "Panama", label: "Panama", phoneCode: "+507" },
  { code: "pg", value: "Papua New Guinea", label: "Papua New Guinea", phoneCode: "+675" },
  { code: "py", value: "Paraguay", label: "Paraguay", phoneCode: "+595" },
  { code: "pe", value: "Peru", label: "Peru", phoneCode: "+51" },
  { code: "ph", value: "Philippines", label: "Philippines", phoneCode: "+63" },
  { code: "pn", value: "Pitcairn", label: "Pitcairn", phoneCode: "+64" },
  { code: "pl", value: "Poland", label: "Poland", phoneCode: "+48" },
  { code: "pt", value: "Portugal", label: "Portugal", phoneCode: "+351" },
  { code: "pr", value: "Puerto Rico", label: "Puerto Rico", phoneCode: "+1787" },
  { code: "qa", value: "Qatar", label: "Qatar", phoneCode: "+974" },
  { code: "re", value: "Réunion", label: "Réunion", phoneCode: "+262" },
  { code: "ro", value: "Romania", label: "Romania", phoneCode: "+40" },
  { code: "ru", value: "Russian Federation", label: "Russian Federation", phoneCode: "+7" },
  { code: "rw", value: "Rwanda", label: "Rwanda", phoneCode: "+250" },
  { code: "bl", value: "St Barthélemy", label: "St Barthélemy", phoneCode: "+590" },
  { code: "sh", value: "St Helena", label: "St Helena", phoneCode: "+290" },
  { code: "kn", value: "St Kitts and Nevis", label: "St Kitts and Nevis", phoneCode: "+1869" },
  { code: "lc", value: "St Lucia", label: "St Lucia", phoneCode: "+1758" },
  { code: "mf", value: "St Martin", label: "St Martin", phoneCode: "+590" },
  { code: "pm", value: "St Pierre and Miquelon", label: "St Pierre and Miquelon", phoneCode: "+508" },
  { code: "vc", value: "St Vincent and the Grenadines", label: "St Vincent and the Grenadines", phoneCode: "+1784" },
  { code: "ws", value: "Samoa", label: "Samoa", phoneCode: "+685" },
  { code: "sm", value: "San Marino", label: "San Marino", phoneCode: "+378" },
  { code: "st", value: "Sao Tome and Principe", label: "Sao Tome and Principe", phoneCode: "+239" },
  { code: "sa", value: "Saudi Arabia", label: "Saudi Arabia", phoneCode: "+966" },
  { code: "sn", value: "Senegal", label: "Senegal", phoneCode: "+221" },
  { code: "rs", value: "Serbia", label: "Serbia", phoneCode: "+381" },
  { code: "sc", value: "Seychelles", label: "Seychelles", phoneCode: "+248" },
  { code: "sl", value: "Sierra Leone", label: "Sierra Leone", phoneCode: "+232" },
  { code: "sg", value: "Singapore", label: "Singapore", phoneCode: "+65" },
  { code: "sx", value: "Sint Maarten", label: "Sint Maarten", phoneCode: "+1721" },
  { code: "sk", value: "Slovakia", label: "Slovakia", phoneCode: "+421" },
  { code: "si", value: "Slovenia", label: "Slovenia", phoneCode: "+386" },
  { code: "sb", value: "Solomon Islands", label: "Solomon Islands", phoneCode: "+677" },
  { code: "so", value: "Somalia", label: "Somalia", phoneCode: "+252" },
  { code: "za", value: "South Africa", label: "South Africa", phoneCode: "+27" },
  // { code: "gs", value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands" },
  { code: "ss", value: "South Sudan", label: "South Sudan", phoneCode: "+211" },
  { code: "es", value: "Spain", label: "Spain", phoneCode: "+34" },
  { code: "lk", value: "Sri Lanka", label: "Sri Lanka", phoneCode: "+94" },
  { code: "sd", value: "Sudan", label: "Sudan", phoneCode: "+249" },
  { code: "sr", value: "Suriname", label: "Suriname", phoneCode: "+597" },
  { code: "sj", value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen", phoneCode: "+47" },
  { code: "se", value: "Sweden", label: "Sweden", phoneCode: "+46" },
  { code: "ch", value: "Switzerland", label: "Switzerland", phoneCode: "+41" },
  { code: "sy", value: "Syrian Arab Republic", label: "Syrian Arab Republic", phoneCode: "+963" },
  { code: "tw", value: "Taiwan", label: "Taiwan", phoneCode: "+886" },
  { code: "tj", value: "Tajikistan", label: "Tajikistan", phoneCode: "+992" },
  { code: "tz", value: "Tanzania", label: "Tanzania", phoneCode: "+255" },
  { code: "th", value: "Thailand", label: "Thailand", phoneCode: "+66" },
  { code: "tl", value: "Timor-Leste", label: "Timor-Leste", phoneCode: "+670" },
  { code: "tg", value: "Togo", label: "Togo", phoneCode: "+228" },
  { code: "tk", value: "Tokelau", label: "Tokelau", phoneCode: "+690" },
  { code: "to", value: "Tonga", label: "Tonga", phoneCode: "+676" },
  { code: "tt", value: "Trinidad and Tobago", label: "Trinidad and Tobago", phoneCode: "+1868" },
  { code: "tn", value: "Tunisia", label: "Tunisia", phoneCode: "+216" },
  { code: "tr", value: "Turkey", label: "Turkey", phoneCode: "+90" },
  { code: "tm", value: "Turkmenistan", label: "Turkmenistan", phoneCode: "+993" },
  { code: "tv", value: "Tuvalu", label: "Tuvalu", phoneCode: "+688" },
  { code: "ug", value: "Uganda", label: "Uganda", phoneCode: "+256" },
  { code: "ua", value: "Ukraine", label: "Ukraine", phoneCode: "+380" },
  { code: "ae", value: "United Arab Emirates", label: "United Arab Emirates", phoneCode: "+971" },
  { code: "gb-ukm", value: "United Kingdom", label: "United Kingdom", phoneCode: "+44" },
  { code: "us", value: "United States", label: "United States", phoneCode: "+1" },
  { code: "uy", value: "Uruguay", label: "Uruguay", phoneCode: "+598" },
  { code: "uz", value: "Uzbekistan", label: "Uzbekistan", phoneCode: "+998" },
  { code: "vu", value: "Vanuatu", label: "Vanuatu", phoneCode: "+678" },
  { code: "ve", value: "Venezuela", label: "Venezuela", phoneCode: "+58" },
  { code: "vn", value: "Viet Nam", label: "Viet Nam", phoneCode: "+84" },
  { code: "vg", value: "Virgin Islands", label: "Virgin Islands", phoneCode: "+1284" },
  { code: "wf", value: "Wallis and Futuna", label: "Wallis and Futuna", phoneCode: "+681" },
  { code: "eh", value: "Western Sahara", label: "Western Sahara", phoneCode: "+212" },
  { code: "ye", value: "Yemen", label: "Yemen", phoneCode: "+967" },
  { code: "zm", value: "Zambia", label: "Zambia", phoneCode: "+260" },
  { code: "zw", value: "Zimbabwe", label: "Zimbabwe", phoneCode: "+263" },
]

export const getCountryByCode = (code: string) => {
  return countries.find((country) => country.code === code)
}